apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.ngnixApp.label }}
  labels:
    app: {{ .Values.ngnixApp.label }}
spec:
  replicas: 3
  template:
    #POD definitin under template, except apiVersion and kind
    metadata:
      name: myapp-pod
      labels:
        app: myapp
    spec:
      containers:
        - name: nginx
          image: nginx
  selector:
    matchLabels:
      app: myapp