apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-config
  namespace: default
  labels:
    k8s-app: fluent-bit
data:
  # Configuration files: server, input, filters and output
  # ======================================================
  # TODO: Parameter tuning (specifically input-kubernetes.conf)
  # TODO: Add custom parsers for Kong/etc?
  fluent-bit.conf: |
    [SERVICE]
        Flush         1
        Log_Level     info
        Daemon        off
        Parsers_File  parsers.conf
        HTTP_Server   On
        HTTP_Listen   0.0.0.0
        HTTP_Port     2020
    @INCLUDE input-kubernetes.conf
    @INCLUDE filter-kubernetes.conf
    @INCLUDE filter-lua.conf
    @INCLUDE filter-modify.conf
    @INCLUDE output-kafka.conf
    @INCLUDE output-stdout.conf
  input-kubernetes.conf: |
    [INPUT]
        Name              tail
        Tag               kube.*
        Path              /var/log/containers/kong-*_default_kong-*.log
        Parser            docker
        DB                /var/log/flb_kube.db
        Mem_Buf_Limit     10MB
        Skip_Long_Lines   On
        Refresh_Interval  10
  filter-kubernetes.conf: |
    [FILTER]
        Name                kubernetes
        Match               kube.*
        Kube_Tag_Prefix     kube.var.log.containers.
        Merge_Log           off
        Merge_Log_Key       log_processed
        K8S-Logging.Parser  On
        K8S-Logging.Exclude On
  filter-lua.conf: |
    [FILTER]
        Name        lua
        Match       kube.*
        script      /fluent-bit/lua/fluent_bit.lua
        call        append_tenant_info
  filter-modify.conf: |
    [FILTER]
        Name          modify
        Match         kube.*
        Set PodName ${FLUENT_BIT_POD_NAME}
        Set PodId ${FLUENT_BIT_POD_ID}    
  output-kafka.conf: |
    [OUTPUT]
        Name           kafka
        Match          *
        Brokers        fsrv1icuswdc040kafka001.fs.local:9096,fsrv1icuswdc040kafka002.fs.local:9096,fsrv1icuswdc040kafka003.fs.local:9096
        Topics         inventory-mgmt-logs
        Timestamp_Key  @timestamp
        Timestamp_Format iso8601
        Retry_Limit    false
        rdkafka.log.connection.close false
        rdkafka.queue.buffering.max.kbytes 10240
        rdkafka.request.required.acks 1
        rdkafka.sasl.mechanism SCRAM-SHA-256
        rdkafka.security.protocol SASL_SSL
        rdkafka.sasl.username inventory-mgmt-w-scram-user
        rdkafka.sasl.password NDNjMDM3MzY4NTcxNzVj
        rdkafka.ssl.ca.location /certs/kafka.keystore.pem
  output-stdout.conf: |        
    [OUTPUT]
        Name  stdout
        Match *        
  parsers.conf: |    
    [PARSER]
        Name        docker
        Format      json
        Time_Key    time
        Time_Format %Y-%m-%dT%H:%M:%S.%L
        Time_Keep   On
