apiVersion: v1
kind: Pod
metadata:
  name: counter
  labels:
    app: counter-pod
    type: log_processer
spec:
  nodeSelector:
    disktype: ssd
  containers:
    - name: count
      image: busybox
      args:
        - /bin/sh
        - -c
        - >
          i=0;
          while true;
          do            
            i=$((i+1));
            sleep 1;
          done      
      volumeMounts:
        - name: varlog
          mountPath: /var/log  
    - name: fluent-bit
      image: fluent/fluent-bit:1.7-debug
      env:
        - name: FLUENT_BIT_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: FLUENT_BIT_POD_ID
          valueFrom:
            fieldRef:
              fieldPath: metadata.uid 
      ports:
        - containerPort: 2020
      volumeMounts:
        - name: varlog
          mountPath: /var/log
        - name: fluent-bit-config
          mountPath: /fluent-bit/etc/
        - name: varlogpods
          mountPath: /var/log/pods
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
        - name: varlibcontainers
          mountPath: /var/lib/containers
          readOnly: true  
        - name: kafka-pem-volume
          mountPath: /certs
        - name: fluent-bit-lua
          mountPath: /fluent-bit/lua
  volumes:
    - name: varlog
      hostPath:
        path: /var/log
    - name: varlogpods
      hostPath:
        path: /var/log/pods
    - name: varlibdockercontainers
      hostPath:
        path: /var/lib/docker/containers
    - name: varlibcontainers
      hostPath:
        path: /var/lib/containers
    - name: fluent-bit-config
      configMap:
        name: fluent-bit-config
    - name: kafka-pem-volume
      configMap:
        defaultMode: 420
        items:
          - key: keystore.pem
            path: kafka.keystore.pem
        name: kafka-pem 
    - name: fluent-bit-lua
      configMap:
        defaultMode: 420
        items:
          - key: luascript
            path: fluent_bit.lua
        name: fluent-bit-lua
    
    
