apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: myapp
spec:
  replicas: 3
  template:
    #POD definitin under template, except apiVersion and kind
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        - name: nginx
          image: nginx
  selector:
    matchLabels:
      app: myapp