apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: application-pipeline
spec:
  resources:
    - name: git-source
      type: git
  params:
    - name: pathToContext
      description: The path to the build context, used by Kaniko - within the workspace
      default: .
    - name: pathToYamlFile
      description: The path to the yaml file to deploy within the git source
      default: kubernetes-yaml-files/tekton/task/nginx-deployment.yaml
  tasks:
  - name: deploy-application
    taskRef:
      name: deploy-application
    params:
      - name: pathToContext
        value: "$(params.pathToContext)"
      - name: pathToYamlFile
        value: "$(params.pathToYamlFile)"
    resources:
      inputs:
        - name: git-source
          resource: git-source
