apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: kong
  namespace: ${NAMESPACE}
spec:
  maxReplicas: 4
  minReplicas: 2
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: kong
  targetCPUUtilizationPercentage: 80
