apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: ticker-consumer
  namespace: ${NAMESPACE}
spec:
  maxReplicas: 4
  minReplicas: 2
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: ticker-consumer
  targetCPUUtilizationPercentage: 80
